version: '3.8'

services:
  web:
    build:
      context: .
      target: builder
    command: yarn dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
    env_file:
      - .env.development